### PR TITLE
Fix deploy-prod, tidy stuff up a bit, use gulp-plumber

### PR DESCRIPTION
**Pull request by garyb**
Also got another change I'll finish up tomorrow morning that makes for faster incremental builds when using the watch tasks.

### CODE REVIEW

**Comment by jdegoes** [comment]
Review / merge by @cryogenian

**Comment by garyb** [comment]
I've added those additional changes for faster bundle updates when watching now too.

**Comment by cryogenian** [comment]
I'm not sure that _watchify_ works faster (I've got browserify running 6 times on one run of `make`), but it's definitely better then browserify :+1: . 
Switched moving from `foo-prod.js` to `foo-prod-builded.js` in `deploy-prod-foo` task. 
Version's bumped.

**Comment by garyb** [comment]
Yeah, the browserify vs watchify difference probably is negligable when we spend so long in `make` anyway. If nothing else, at least `deploy-prod` works as intended now!

Thanks :+1:

**Pull request merged**
